/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const JobStatus = IDL.Variant({
  'completed' : IDL.Record({
    'blob' : ExternalBlob,
    'processingTime' : Time,
    'uploadTime' : Time,
  }),
  'processing' : IDL.Record({ 'uploadTime' : Time }),
});
export const ConversionJob = IDL.Record({
  'status' : JobStatus,
  'creator' : IDL.Principal,
  'inputVoiceAudio' : ExternalBlob,
  'targetVoiceId' : IDL.Text,
  'sourceVoiceId' : IDL.Text,
});
export const VoiceModel = IDL.Record({
  'snapshotTime' : Time,
  'creator' : IDL.Principal,
  'audio' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VoiceModelWithId = IDL.Record({
  'id' : IDL.Text,
  'model' : VoiceModel,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeVoiceConversionJob' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'deleteVoiceModel' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllConversionJobs' : IDL.Func([], [IDL.Vec(ConversionJob)], ['query']),
  'getAllVoiceModels' : IDL.Func([], [IDL.Vec(VoiceModel)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(ConversionJob)], ['query']),
  'getOwnVoiceModelsWithIds' : IDL.Func(
      [],
      [IDL.Vec(VoiceModelWithId)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoiceModel' : IDL.Func([IDL.Text], [IDL.Opt(VoiceModel)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeVoiceConversionJob' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadNewVoiceModel' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const JobStatus = IDL.Variant({
    'completed' : IDL.Record({
      'blob' : ExternalBlob,
      'processingTime' : Time,
      'uploadTime' : Time,
    }),
    'processing' : IDL.Record({ 'uploadTime' : Time }),
  });
  const ConversionJob = IDL.Record({
    'status' : JobStatus,
    'creator' : IDL.Principal,
    'inputVoiceAudio' : ExternalBlob,
    'targetVoiceId' : IDL.Text,
    'sourceVoiceId' : IDL.Text,
  });
  const VoiceModel = IDL.Record({
    'snapshotTime' : Time,
    'creator' : IDL.Principal,
    'audio' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VoiceModelWithId = IDL.Record({
    'id' : IDL.Text,
    'model' : VoiceModel,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeVoiceConversionJob' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'deleteVoiceModel' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllConversionJobs' : IDL.Func([], [IDL.Vec(ConversionJob)], ['query']),
    'getAllVoiceModels' : IDL.Func([], [IDL.Vec(VoiceModel)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(ConversionJob)], ['query']),
    'getOwnVoiceModelsWithIds' : IDL.Func(
        [],
        [IDL.Vec(VoiceModelWithId)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoiceModel' : IDL.Func([IDL.Text], [IDL.Opt(VoiceModel)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeVoiceConversionJob' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadNewVoiceModel' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };