/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VoiceModelId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ConversionJobId = IDL.Nat;
export const ConversionJobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const ConversionJob = IDL.Record({
  'id' : ConversionJobId,
  'status' : ConversionJobStatus,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'inputAudio' : ExternalBlob,
  'resultAudio' : IDL.Opt(ExternalBlob),
  'modelId' : VoiceModelId,
});
export const ModelMetadata = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'trainingData' : IDL.Vec(IDL.Text),
  'format' : IDL.Text,
});
export const VoiceModel = IDL.Record({
  'id' : VoiceModelId,
  'owner' : IDL.Principal,
  'metadata' : ModelMetadata,
  'storage' : ExternalBlob,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversionJob' : IDL.Func(
      [VoiceModelId, ExternalBlob],
      [ConversionJobId],
      [],
    ),
  'deleteVoiceModel' : IDL.Func([VoiceModelId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversionJob' : IDL.Func(
      [ConversionJobId],
      [IDL.Opt(ConversionJob)],
      ['query'],
    ),
  'getConversionJobsByOwner' : IDL.Func(
      [],
      [IDL.Vec(ConversionJob)],
      ['query'],
    ),
  'getVoiceModel' : IDL.Func([VoiceModelId], [IDL.Opt(VoiceModel)], ['query']),
  'getVoiceModelsByOwner' : IDL.Func([], [IDL.Vec(VoiceModel)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processConversionJob' : IDL.Func([ConversionJobId], [], []),
  'uploadVoiceModel' : IDL.Func(
      [ModelMetadata, ExternalBlob],
      [VoiceModelId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VoiceModelId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ConversionJobId = IDL.Nat;
  const ConversionJobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const ConversionJob = IDL.Record({
    'id' : ConversionJobId,
    'status' : ConversionJobStatus,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
    'inputAudio' : ExternalBlob,
    'resultAudio' : IDL.Opt(ExternalBlob),
    'modelId' : VoiceModelId,
  });
  const ModelMetadata = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'trainingData' : IDL.Vec(IDL.Text),
    'format' : IDL.Text,
  });
  const VoiceModel = IDL.Record({
    'id' : VoiceModelId,
    'owner' : IDL.Principal,
    'metadata' : ModelMetadata,
    'storage' : ExternalBlob,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversionJob' : IDL.Func(
        [VoiceModelId, ExternalBlob],
        [ConversionJobId],
        [],
      ),
    'deleteVoiceModel' : IDL.Func([VoiceModelId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversionJob' : IDL.Func(
        [ConversionJobId],
        [IDL.Opt(ConversionJob)],
        ['query'],
      ),
    'getConversionJobsByOwner' : IDL.Func(
        [],
        [IDL.Vec(ConversionJob)],
        ['query'],
      ),
    'getVoiceModel' : IDL.Func(
        [VoiceModelId],
        [IDL.Opt(VoiceModel)],
        ['query'],
      ),
    'getVoiceModelsByOwner' : IDL.Func([], [IDL.Vec(VoiceModel)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processConversionJob' : IDL.Func([ConversionJobId], [], []),
    'uploadVoiceModel' : IDL.Func(
        [ModelMetadata, ExternalBlob],
        [VoiceModelId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };