/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversionJob {
  'id' : ConversionJobId,
  'status' : ConversionJobStatus,
  'owner' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'inputAudio' : ExternalBlob,
  'resultAudio' : [] | [ExternalBlob],
  'modelId' : VoiceModelId,
}
export type ConversionJobId = bigint;
export type ConversionJobStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type ExternalBlob = Uint8Array;
export interface ModelMetadata {
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'trainingData' : Array<string>,
  'format' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceModel {
  'id' : VoiceModelId,
  'owner' : Principal,
  'metadata' : ModelMetadata,
  'storage' : ExternalBlob,
  'createdAt' : Time,
}
export type VoiceModelId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConversionJob' : ActorMethod<
    [VoiceModelId, ExternalBlob],
    ConversionJobId
  >,
  'deleteVoiceModel' : ActorMethod<[VoiceModelId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversionJob' : ActorMethod<[ConversionJobId], [] | [ConversionJob]>,
  'getConversionJobsByOwner' : ActorMethod<[], Array<ConversionJob>>,
  'getVoiceModel' : ActorMethod<[VoiceModelId], [] | [VoiceModel]>,
  'getVoiceModelsByOwner' : ActorMethod<[], Array<VoiceModel>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processConversionJob' : ActorMethod<[ConversionJobId], undefined>,
  'uploadVoiceModel' : ActorMethod<[ModelMetadata, ExternalBlob], VoiceModelId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];